openapi: 3.0.0
x-stoplight:
  id: 76ay3eio5thkt
info:
  title: sandbox_app_backend_api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/teams/{team_id}/users':
    parameters:
      - schema:
          type: string
        name: team_id
        in: path
        required: true
    get:
      summary: get team users
      tags:
        - sandbox_app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    x-stoplight:
                      id: 9to814z3mhrsc
                    items:
                      $ref: ../models/User.yaml
                      x-stoplight:
                        id: l3b05mynt3wt6
                required:
                  - users
                additionalProperties: false
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../models/ResponseErrorBase.yaml
      operationId: get-teams-teamId-users
      requestBody:
        content: {}
  /teams:
    get:
      summary: get teams
      tags:
        - sandbox_app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams:
                    type: array
                    x-stoplight:
                      id: z455bdcdb6fn0
                    items:
                      $ref: ../models/Team.yaml
                      x-stoplight:
                        id: ehiirrtxaaxln
                required:
                  - teams
                additionalProperties: false
      operationId: get-teams
      parameters:
        - schema:
            type: string
          in: query
          name: search_keyword
        - schema:
            type: array
          in: query
          name: user_ids
          style: form
          explode: true
      description: ''
  '/teams/{team_id}/users/bulk':
    parameters:
      - schema:
          type: string
        name: team_id
        in: path
        required: true
    patch:
      summary: bulk update users
      tags:
        - sandbox_app
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: patch-teams-team_id-users-bulk
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  x-stoplight:
                    id: fbnm15b7vk4b2
                  items:
                    x-stoplight:
                      id: jhslr847gegs5
                    type: object
                    minProperties: 0
                    maxProperties: 0
                    properties:
                      id:
                        type: integer
                        x-stoplight:
                          id: zpfpqlh86sdi6
                      first_name:
                        type: string
                        x-stoplight:
                          id: 9e249530yrdfk
                    required:
                      - id
                      - first_name
              required:
                - users
        description: ''
components:
  schemas: {}
tags:
  - name: sandbox_app
